<a href="https://colab.research.google.com/github/jungmin628/SummerWorkshop/blob/master/%ED%8C%80%EA%B3%BC%EC%A0%9C_week01_%EC%9D%B4%EC%A0%95%EB%AF%BC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1번
a,b = input('입력').split();
result_a = int(a)
result_b = int(b)
result = result_a/result_b
print('%.20f' %result)

입력3 7
0.42857142857142854764


In [ ]:
# 2번
result_sum = int(input("서로다른 자연수 N개의 자연수 합은?"))
cnt = 0
sum = 0
for kk in range(result_sum):
  cnt=cnt+1
  sum = sum+cnt
  if(sum == result_sum):
    print(cnt)
    break
  elif(sum > result_sum):
    cnt=cnt-1
    print(cnt)
    break

서로다른 자연수 N개의 자연수 합은?19
5


In [37]:
# 3번
# 미완성
import numpy as np
while True:
  num = int(input('행렬의 크기를 입력하세요'))
  if(num%2 == 0):
    break
  else:
    print("짝수의 수로 다시 입력하세요.")
    continue
array = np.random.randint(0,100, size = (2**num,2**num))
print(array)
max = int(array[0][0])
second = 0
while True:
  if(num>2):
    for i in range(num):
      for j in range(num):
        if(max<array[i][j]):
          second = max
          max = array[i][j]
        elif(second<array[i][j]<max):
          second = array[i][j]
    array2 = np.array([])
    array2 = np.append(array2, second)
  else:

print(array2)

행렬의 크기를 입력하세요3
짝수의 수로 다시 입력하세요.
행렬의 크기를 입력하세요4
[[16 33 35 84 77 41 79 65 28 96 35 48 90 80 83 99]
 [ 9 14  5 83 17 27 88 38 19 69 23 25 34 14 65 61]
 [35  3 93 28 17 69 48 93 56 40 29 96 85 91 47 93]
 [81 20 95 16 35 70  8 35 50 29 35 48 46 52 93 21]
 [ 1 56 97 99 79 89  5 74  1  5 33 95 95 90 98 17]
 [54 13 67 90 15 93  6 28 19 71 36 66 66 37 51 88]
 [22 29 38 84 52 57 28 53 62 79 14 18 69 43 47 56]
 [11 27 94 12 22 68 16 65 92 78 48 94 61 98  1 40]
 [ 4 46 23 43 35 11 52 98 48 91 25 82 55 55 73 65]
 [93 27 36 32 87 80 28 18  0 32 32 80  2 17 43 34]
 [33 16 15 67  3 17 77 10  6 65 91 87 19  5 74 85]
 [90 22 43  4 46 51 20 56 61 92 86 13 86 93 49 99]
 [ 4 86 24 90 52 88 93 87 14 86  0 59 18 84 92 72]
 [20 52 40 40 33 51 13 12 51 18 67  1 14 86 12  4]
 [89 21 41 35 78 72 38 91 96 58 97 97  1 23 69 76]
 [23 72 20 92 93 14 92 93  4 94 80 10 38 93 48  7]]
[93.]
